### ISSUE TITLE
HTML escaping errors and admin pay error

### ISSUE THREAD

**Issue by DanielHudson2** [globalpayments/globalpayments-woocommerce#44]
the latest version has html escaping errors which are visible to users on the admin order page

![Image](https://github.com/user-attachments/assets/a22128a4-3652-4802-aeef-8d49e14c97e4)

there is also an error in the console on admin pages:

![Image](https://github.com/user-attachments/assets/1f6fb197-4a10-4e2b-9385-6be20a8797dc)

This error is preventing the pay for order button from functioning because the whole javascript file stops running when it hits the error, the error is on [this line](https://github.com/globalpayments/globalpayments-woocommerce/blob/master/assets/admin/js/globalpayments-admin.js#L33) it is checking the api credentials on load but those fields don't exist on the order page, if i comment this out the modal works again but also has a html escaping error on it 

![Image](https://github.com/user-attachments/assets/37b191cf-7ecc-4b33-ac66-dd3e10874048)

The version number on the plugin file also doesnt match your release number in the repository

**Comment by rerwin03** [comment]
Good afternoon, 

I have raised this issue with our development team. For awareness, a fix was released for this issue but was only done so via our Heartland specific version of WooCommerce.  If you are connected to Global Payments via our Heartland connection, you should be able to utilize [v3.02](https://github.com/hps/heartland-woocommerce-plugin) of our plugin. In the meantime, I will ask the team to look into this same issue on our gateway agnostic version of the plugin.

Thank you,
Rob Erwin

**Comment by rerwin-collab** [comment]
Good morning @DanielHudson2,

I sincerely appreciate your patience while the team looked into this report. I have been advised that the HTML escaping issues should be resolved as of v1.14.7 (see below). Please update the GP WooCommerce plugin and advise if the update has resolved this issue or if the issue persists. 

<img width="1305" height="515" alt="Image" src="https://github.com/user-attachments/assets/8c8060c3-a8f1-4996-aff5-20d76c77b1f7" />

Thank you

**Comment by Aseela-Ali** [comment]
Hi @rerwin-collab, thanks for the update. I’ve tested with v1.14.7 on my staging site and I’m still seeing the same issue with the “Pay for Order” button.

The modal does not load.

Console shows:
_Uncaught TypeError: Cannot read properties of undefined (reading 'trim')
    at GlobalPaymentsAdmin.getGatewaySetting_
I’ve attached a screenshot for reference (from v1.14.7). Please let me know if you’d like any additional logs from my staging environment.

Thanks again for your support.

<img width="1742" height="273" alt="Image" src="https://github.com/user-attachments/assets/616fbbed-e4a4-4747-b040-bed9127c45fd" />

**Comment by rerwin-collab** [comment]
@Aseela-Ali Could you please send the following information to developers@globalpay.com for further review?

Environment (Sandbox or Production): 

Shopping Cart: WooCommerce

Wordpress Version: 

Plugin Version: 1.14.7

Unified Payments, Portico, Genius/Merchantware, TSYS, or GP-Ecom (HPP): 

Code Sample, logs, screenshots, or videos: Attach a Zip file

I might also ask if you would mind granting Global Payments temporary admin access to your Wordpress environment to review website design and plugin stack to help us try to recreate the current environment? Please advise as time permits.

Thank you

**Comment by farwestdev** [comment]
We've been struggling with the same issue for the "Pay for Order" button for some of our clients too. It looks like later versions are trying to pull up settings that simply don't exist because they are not rendered in the DOM. Looks like the JS code is trying to pull up values using element id to input fields from the Global Payments settings page, but they do not exist in the admin order pages.

Functions in `globalpayments-admin.js` like `isLiveMode()` always returns `false` and `getGatewaySetting()` will generally error out as `.val()` returns undefined and `.trim()` will cause the error as detailed by @Aseela-Ali 

The screenshot by @Aseela-Ali should already be enough information to fix this problem.

We are currently using the Unified Payments option. The current workaround for us is to simply hardcode the the `app_id` and `app_key` using our own PHP plugin to make the hidden input fields with the element id's `woocommerce_globalpayments_gpapi_app_id` and `woocommerce_globalpayments_gpapi_app_key` available on the admin orders p[age.

`isLiveMode()` is also modified as I didn't want to dig into how the `this.id` is retrieved in `getLiveModeSelector()`:

```JS
isLiveMode: function() {
	if ( !$( this.getLiveModeSelector() ).length ) return true;  // Return true if it can't find the setting using selector
	return $( this.getLiveModeSelector() ).is( ':checked' );
}
```

**Comment by rerwin03** [comment]
@DanielHudson2, @Aseela-Ali, or @farwestdev Could you advise if this issue is still present in our latest version v1.16.4? 

Best regards

**Comment by farwestdev** [comment]
@rerwin03 yes, 1.16.4

**Comment by rerwin03** [comment]
Thank you @farwestdev for the confirmation. I've raised this with our engineers to revisit.

**Comment by Aseela-Ali** [comment]
@rerwin03  Yes, still happening on v1.16.4 for me.

Staging: WP 6.8.2 / WC 10.1.2 / PHP 8.2.
“Pay for Order” modal doesn’t open, console shows: Cannot read properties of undefined (reading 'trim') in globalpayments-admin.js.
Using Unified Payments (GPAPI).

**Comment by rerwin03** [comment]
Thank you @Aseela-Ali for the confirmation and sharing the versioning. This could be helpful when trying to recreate. I've raised this with our engineers to revisit.
